ALTER TABLE company_settings
  ADD COLUMN IF NOT EXISTS company_street TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS company_zip TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS company_city TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS company_phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS company_email TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS company_tax_number TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS company_vat_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS company_managing_director TEXT NOT NULL DEFAULT '';
